import { ReactElement, useEffect, useState } from 'react';
import ListingItem from '@ui/ListingItem';
import { Wrapper } from '@ui/Wrapper';
import Head from 'next/head';
import { productListings } from 'src/data';
import { initializeLocalStorage } from 'src/helpers/helpers';
import { Layout } from 'src/layouts';
import { getItem } from 'src/utils/AsyncStorage';

import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const [listings, setListings] = useState(productListings);
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    initializeLocalStorage('ListingData');

    const listingsJSON = getItem('ListingData');
    if (listingsJSON) {
      setListings(JSON.parse(listingsJSON));
    }
  }, []);

  // Render only if the component is mounted
  if (!isMounted) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Stackblud Assesment App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex flex-wrap gap-4 p-7">
        {listings.map((productListing) => (
          <ListingItem
            key={productListing.id}
            productListing={productListing}
          />
        ))}
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
